<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AxiomPlayground.Data</RootNamespace>
  </PropertyGroup>

  <!-- Dev configuration -->
  <PropertyGroup Condition="'$(Configuration)'=='Dev'">
    <DefineConstants>DEV_ENV;TRACE</DefineConstants>
    <OutputPath>../../lib/Dev/</OutputPath>
  </PropertyGroup>

  <!-- Release configuration -->
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>TRACE</DefineConstants>
    <OutputPath>../../lib/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GameFlag/GameFlag.csproj" />
    <ProjectReference Include="../Modding/Modding.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MoonSharp.Interpreter">
      <HintPath>../../lib/Dev/net10.0/MoonSharp.Interpreter.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
